feat: Adding release documentation for NGINX Agent Integration
nginxinc/nginx-amplify-doc pull request #80
Opened 2023-08-22 19:37 UTC by richbrowne

Updating known issues and what's new for Amplify support for the NGINX Agent.

2023-08-22 20:24 UTC, bheftel commented on content/changelog.md
> +  The NGINX Amplify team is pleased to announce beta support for the [NGINX Agent](https://github.com/nginx/agent).  The NGINX Agent is an open source companion daemon for your NGINX Open Source or N
do all instances of "NGINX Agent" need to be bolded?

2023-08-22 21:48 UTC, richbrowne commented on content/changelog.md
> +  The NGINX Amplify team is pleased to announce beta support for the [NGINX Agent](https://github.com/nginx/agent).  The NGINX Agent is an open source companion daemon for your NGINX Open Source or N
Not sure.  I will look at existing docs to see what the pattern is.  Thanks.

2023-08-25 15:03 UTC, travisamartin commented on content/known-issues.md
> +The **NGINX Agent** can only manage one **NGINX** instance per system.
```suggestion
The NGINX Agent can only manage one NGINX instance per system.
```

2023-08-25 15:04 UTC, travisamartin commented on content/known-issues.md
> +**NGINX Agent** does not support [metric filters](https://docs.nginx.com/nginx-amplify/user-interface/dashboards/).  If your NGINX instance is managed by the NGINX Agent, you will not be able to add
```suggestion
The NGINX Agent does not support [metric filters](https://docs.nginx.com/nginx-amplify/user-interface/dashboards/).  If the NGINX Agent manages your NGINX instance, you cannot add a metric filter when you create a custom dashboard.
```

2023-08-25 15:05 UTC, travisamartin commented on content/known-issues.md
> +When using the nginx-agent, host connectivity alerts may reference the incorrect server.
```suggestion
Host connectivity alerts may reference the incorrect server when using the NGINX Agent.
```

2023-08-25 15:05 UTC, travisamartin commented on content/known-issues.md
> +The correct server to check connectivity is receiver-grpc.amplify.nginx.com.
```suggestion
The correct server to check connectivity is `receiver-grpc.amplify.nginx.com`.
```

2023-08-25 15:05 UTC, travisamartin commented on content/known-issues.md
> +NGINX Agent does not support reporting the plus.* metrics per zone but it can be used to display a cumulative sum of values from each zone.
```suggestion
NGINX Agent does not support reporting the `plus.*` metrics per zone, but it can be used to display a cumulative sum of values from each zone.
```

2023-08-25 15:07 UTC, travisamartin commented on content/known-issues.md
> +Amplify will not be able to perform configuration analysis for NGINX instances mananged by the NGINX agent when the root NGINX configuration file is not named `nginx.conf`.
```suggestion
Amplify cannot perform configuration analysis for NGINX instances managed by the NGINX agent when the root NGINX configuration file is not named `nginx.conf`.
```

2023-08-25 15:07 UTC, travisamartin commented on content/known-issues.md
> +The Amplify Agent is not impacted by this issue.
```suggestion
This issue does not affect the Amplify Agent.
```

2023-08-25 15:08 UTC, travisamartin requested changes
Approved w/ suggested edits.

2023-08-25 15:27 UTC, richbrowne commented
@travisamartin Thank you very much for your comments.  I have a question about the Known issues that are feature gaps and not bugs.  I see you included a {{ feature-icon }} recommendation in the review.  Could I prefix each feature gap in the Known Issues with this icon?  Thanks.

Also, when should I put NGINX Agent with bold emphasis?  I will ask this question in the friends of the docs channel.

2023-08-25 16:24 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not support PHP-FPM metrics. {#647}
```suggestion
### {{% icon-bug %}} NGINX Agent does not support PHP-FPM metrics. {#647}
```

2023-08-25 16:24 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not support MySQL metrics. {#648}
```suggestion
### {{% icon-bug %}} NGINX Agent does not support MySQL metrics. {#648}
```

2023-08-25 16:24 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not support Agent metrics. {#650}
```suggestion
### {{% icon-bug %}} NGINX Agent does not support Agent metrics. {#650}
```

2023-08-25 16:24 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not support remote Agent Settings. {#679}
```suggestion
### {{% icon-bug %}} NGINX Agent does not support remote Agent Settings. {#679}
```

2023-08-25 16:25 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not perform periodic `nginx -t`. {#711}
```suggestion
### {{% icon-bug %}} NGINX Agent does not perform periodic `nginx -t`. {#711}
```

2023-08-25 16:25 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not manage multiple NGINX instances. {#683}
```suggestion
### {{% icon-bug %}} NGINX Agent does not manage multiple NGINX instances. {#683}
```

2023-08-25 16:25 UTC, travisamartin commented on content/known-issues.md
> +### NGINX Agent does not support Metric Filters. {#680}
```suggestion
### {{% icon-bug %}} NGINX Agent does not support Metric Filters. {#680}
```

2023-08-25 16:27 UTC, travisamartin commented
The known issues doc uses `{{% icon-bug %}}` for bugs and feature gaps and `{{% icon-resolved %}} for fixed issues. I added suggested edits to include the missing icons. Sorry I didn't catch that the first time.

There's no special styling for product names -- just plain text.

2023-08-25 20:34 UTC, travisamartin approved these changes

2023-08-25 20:34 UTC, merged